[unifi]
hostname = "https://192.168.0.1"
username = ""
password = ""
interval = 10

[network]
devices = [
    "00:00:00:00:00:00" # Example-Device
]

[protect]
camera = "XXXXXXXXXXXXXXXXXXXXXXXX"

[telegram]
bot_token = "XXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXX"
chat_id = "XXXXXXXXXX"
startup_msg = true